//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestAssoc.Modules.GestionVilles.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestAssoc.Modules.GestionVilles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer la ville suivante?.
        /// </summary>
        public static string Confirm_SuppressionVille {
            get {
                return ResourceManager.GetString("Confirm_SuppressionVille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code postal obligatoire..
        /// </summary>
        public static string Err_CodePostalObligatoire {
            get {
                return ResourceManager.GetString("Err_CodePostalObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom obligatoire..
        /// </summary>
        public static string Err_LibelleObligatoire {
            get {
                return ResourceManager.GetString("Err_LibelleObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette ville existe déjà (code postal + nom)..
        /// </summary>
        public static string Err_VilleExiste {
            get {
                return ResourceManager.GetString("Err_VilleExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string Header_Actions {
            get {
                return ResourceManager.GetString("Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        public static string Header_Details {
            get {
                return ResourceManager.GetString("Header_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Villes.
        /// </summary>
        public static string Header_List {
            get {
                return ResourceManager.GetString("Header_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats.
        /// </summary>
        public static string Header_Statistiques {
            get {
                return ResourceManager.GetString("Header_Statistiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code postal : .
        /// </summary>
        public static string Label_CodePostal {
            get {
                return ResourceManager.GetString("Label_CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom : .
        /// </summary>
        public static string Label_Libelle {
            get {
                return ResourceManager.GetString("Label_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. filtrée(s) : .
        /// </summary>
        public static string Label_NbFiltre {
            get {
                return ResourceManager.GetString("Label_NbFiltre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. total : .
        /// </summary>
        public static string Label_NbTotal {
            get {
                return ResourceManager.GetString("Label_NbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage du RibbonTab GestionVilles.
        /// </summary>
        public static string Log_AffichageMenu {
            get {
                return ResourceManager.GetString("Log_AffichageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage de la vue .
        /// </summary>
        public static string Log_AffichageVue {
            get {
                return ResourceManager.GetString("Log_AffichageVue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville non valide. Enregistrement annulé..
        /// </summary>
        public static string Log_EnregistrementAnnule {
            get {
                return ResourceManager.GetString("Log_EnregistrementAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville enregistrée..
        /// </summary>
        public static string Log_EnregistrementEffectue {
            get {
                return ResourceManager.GetString("Log_EnregistrementEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville supprimée..
        /// </summary>
        public static string Log_EnregistrementSupprime {
            get {
                return ResourceManager.GetString("Log_EnregistrementSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation du Module GestionVilles..
        /// </summary>
        public static string Log_InitialisationModule {
            get {
                return ResourceManager.GetString("Log_InitialisationModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle ville.
        /// </summary>
        public static string MenuButton_Add {
            get {
                return ResourceManager.GetString("MenuButton_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consulter.
        /// </summary>
        public static string MenuButton_List {
            get {
                return ResourceManager.GetString("MenuButton_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des villes.
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Villes.
        /// </summary>
        public static string Titre_Consultation {
            get {
                return ResourceManager.GetString("Titre_Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        public static string Titre_Formulaire {
            get {
                return ResourceManager.GetString("Titre_Formulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisie invalide.
        /// </summary>
        public static string Titre_SaisieInvalide {
            get {
                return ResourceManager.GetString("Titre_SaisieInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string Tooltip_Ajouter {
            get {
                return ResourceManager.GetString("Tooltip_Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Tooltip_Annuler {
            get {
                return ResourceManager.GetString("Tooltip_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer.
        /// </summary>
        public static string Tooltip_Editer {
            get {
                return ResourceManager.GetString("Tooltip_Editer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string Tooltip_Enregistrer {
            get {
                return ResourceManager.GetString("Tooltip_Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Tooltip_Supprimer {
            get {
                return ResourceManager.GetString("Tooltip_Supprimer", resourceCulture);
            }
        }
    }
}
