//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestAssoc.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ville
    {
        public Ville()
        {
            this.InfosClubs = new HashSet<InfosClub>();
        }
    
        public System.Guid ID { get; set; }
        public string Libelle { get; set; }
        public string CodePostal { get; set; }
    
        public virtual ICollection<InfosClub> InfosClubs { get; set; }
    }
}
