//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestAssoc.Modules.GestionAdhesions.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestAssoc.Modules.GestionAdhesions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer l&apos;adhérent suivant?.
        /// </summary>
        public static string Confirm_Adh_Suppression {
            get {
                return ResourceManager.GetString("Confirm_Adh_Suppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer le groupe suivant?.
        /// </summary>
        public static string Confirm_Grp_Suppression {
            get {
                return ResourceManager.GetString("Confirm_Grp_Suppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer l&apos;inscription suivante?.
        /// </summary>
        public static string Confirm_Ins_Suppression {
            get {
                return ResourceManager.GetString("Confirm_Ins_Suppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer la saison suivante?.
        /// </summary>
        public static string Confirm_Sai_Suppression {
            get {
                return ResourceManager.GetString("Confirm_Sai_Suppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer la ville suivante?.
        /// </summary>
        public static string Confirm_Vil_Suppression {
            get {
                return ResourceManager.GetString("Confirm_Vil_Suppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse obligatoire..
        /// </summary>
        public static string Err_Adh_AdresseObligatoire {
            get {
                return ResourceManager.GetString("Err_Adh_AdresseObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date de naissance saisie est trop ancienne pour le système..
        /// </summary>
        public static string Err_Adh_DateNaissanceTropAncienne {
            get {
                return ResourceManager.GetString("Err_Adh_DateNaissanceTropAncienne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet adhérent existe déjà (nom + prénom)..
        /// </summary>
        public static string Err_Adh_Existe {
            get {
                return ResourceManager.GetString("Err_Adh_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance obligatoire..
        /// </summary>
        public static string Err_Adh_NaissanceObligatoire {
            get {
                return ResourceManager.GetString("Err_Adh_NaissanceObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom obligatoire..
        /// </summary>
        public static string Err_Adh_NomObligatoire {
            get {
                return ResourceManager.GetString("Err_Adh_NomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom obligatoire..
        /// </summary>
        public static string Err_Adh_PrenomObligatoire {
            get {
                return ResourceManager.GetString("Err_Adh_PrenomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VilleObligatoire..
        /// </summary>
        public static string Err_Adh_VilleObligatoire {
            get {
                return ResourceManager.GetString("Err_Adh_VilleObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce groupe existe déjà (nom + créneau)..
        /// </summary>
        public static string Err_Grp_Existe {
            get {
                return ResourceManager.GetString("Err_Grp_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure de fin doit être strictement supérieure à l&apos;heure de début..
        /// </summary>
        public static string Err_Grp_HeureDebutHeureFin {
            get {
                return ResourceManager.GetString("Err_Grp_HeureDebutHeureFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure de début obligatoire..
        /// </summary>
        public static string Err_Grp_HeureDebutObligatoire {
            get {
                return ResourceManager.GetString("Err_Grp_HeureDebutObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure de fin obligatoire..
        /// </summary>
        public static string Err_Grp_HeureFinObligatoire {
            get {
                return ResourceManager.GetString("Err_Grp_HeureFinObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom obligatoire..
        /// </summary>
        public static string Err_Grp_LibelleObligatoire {
            get {
                return ResourceManager.GetString("Err_Grp_LibelleObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent obligatoire..
        /// </summary>
        public static string Err_Ins_AdherentObligatoire {
            get {
                return ResourceManager.GetString("Err_Ins_AdherentObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe obligatoire..
        /// </summary>
        public static string Err_Ins_GroupeObligatoire {
            get {
                return ResourceManager.GetString("Err_Ins_GroupeObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette inscription existe déjà (adhérent + groupe)..
        /// </summary>
        public static string Err_Ins_InscriptionExiste {
            get {
                return ResourceManager.GetString("Err_Ins_InscriptionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;année de fin doit être supérieure à l&apos;année de début..
        /// </summary>
        public static string Err_Sai_AnneeDebutAnneeFin {
            get {
                return ResourceManager.GetString("Err_Sai_AnneeDebutAnneeFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette saison existe déjà (année début + année fin)..
        /// </summary>
        public static string Err_Sai_Existe {
            get {
                return ResourceManager.GetString("Err_Sai_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code postal obligatoire..
        /// </summary>
        public static string Err_Vil_CodePostalObligatoire {
            get {
                return ResourceManager.GetString("Err_Vil_CodePostalObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette ville existe déjà (nom + code postal)..
        /// </summary>
        public static string Err_Vil_Existe {
            get {
                return ResourceManager.GetString("Err_Vil_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom obligatoire..
        /// </summary>
        public static string Err_Vil_LibelleObligatoire {
            get {
                return ResourceManager.GetString("Err_Vil_LibelleObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string Header_Actions {
            get {
                return ResourceManager.GetString("Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérents.
        /// </summary>
        public static string Header_Adh_List {
            get {
                return ResourceManager.GetString("Header_Adh_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        public static string Header_Details {
            get {
                return ResourceManager.GetString("Header_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupes.
        /// </summary>
        public static string Header_Grp_List {
            get {
                return ResourceManager.GetString("Header_Grp_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent.
        /// </summary>
        public static string Header_Ins_Adherent {
            get {
                return ResourceManager.GetString("Header_Ins_Adherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string Header_Ins_Inscription {
            get {
                return ResourceManager.GetString("Header_Ins_Inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscriptions.
        /// </summary>
        public static string Header_Ins_List {
            get {
                return ResourceManager.GetString("Header_Ins_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisons.
        /// </summary>
        public static string Header_Sai_List {
            get {
                return ResourceManager.GetString("Header_Sai_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats.
        /// </summary>
        public static string Header_Statistiques {
            get {
                return ResourceManager.GetString("Header_Statistiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Villes.
        /// </summary>
        public static string Header_Vil_List {
            get {
                return ResourceManager.GetString("Header_Vil_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse : .
        /// </summary>
        public static string Label_Adh_Adresse {
            get {
                return ResourceManager.GetString("Label_Adh_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à an(s).
        /// </summary>
        public static string Label_Adh_Ans {
            get {
                return ResourceManager.GetString("Label_Adh_Ans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mails : .
        /// </summary>
        public static string Label_Adh_Emails {
            get {
                return ResourceManager.GetString("Label_Adh_Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance : .
        /// </summary>
        public static string Label_Adh_Naissance {
            get {
                return ResourceManager.GetString("Label_Adh_Naissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom / prénom : .
        /// </summary>
        public static string Label_Adh_NomPrenom {
            get {
                return ResourceManager.GetString("Label_Adh_NomPrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sexe : .
        /// </summary>
        public static string Label_Adh_Sexe {
            get {
                return ResourceManager.GetString("Label_Adh_Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphones : .
        /// </summary>
        public static string Label_Adh_Telephones {
            get {
                return ResourceManager.GetString("Label_Adh_Telephones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville : .
        /// </summary>
        public static string Label_Adh_Ville {
            get {
                return ResourceManager.GetString("Label_Adh_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaires : .
        /// </summary>
        public static string Label_Commentaire {
            get {
                return ResourceManager.GetString("Label_Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créneau : .
        /// </summary>
        public static string Label_Grp_Creneau {
            get {
                return ResourceManager.GetString("Label_Grp_Creneau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure de début : .
        /// </summary>
        public static string Label_Grp_HeureDebut {
            get {
                return ResourceManager.GetString("Label_Grp_HeureDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure de fin : .
        /// </summary>
        public static string Label_Grp_HeureFin {
            get {
                return ResourceManager.GetString("Label_Grp_HeureFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jour : .
        /// </summary>
        public static string Label_Grp_Jour {
            get {
                return ResourceManager.GetString("Label_Grp_Jour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. places : .
        /// </summary>
        public static string Label_Grp_NbPlaces {
            get {
                return ResourceManager.GetString("Label_Grp_NbPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom : .
        /// </summary>
        public static string Label_Grp_Nom {
            get {
                return ResourceManager.GetString("Label_Grp_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saison : .
        /// </summary>
        public static string Label_Grp_Saison {
            get {
                return ResourceManager.GetString("Label_Grp_Saison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent : .
        /// </summary>
        public static string Label_Ins_Adherent {
            get {
                return ResourceManager.GetString("Label_Ins_Adherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à an(s).
        /// </summary>
        public static string Label_Ins_Ans {
            get {
                return ResourceManager.GetString("Label_Ins_Ans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificat médical :.
        /// </summary>
        public static string Label_Ins_CertificatMedical {
            get {
                return ResourceManager.GetString("Label_Ins_CertificatMedical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cotisation : .
        /// </summary>
        public static string Label_Ins_Cotisation {
            get {
                return ResourceManager.GetString("Label_Ins_Cotisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe : .
        /// </summary>
        public static string Label_Ins_Groupe {
            get {
                return ResourceManager.GetString("Label_Ins_Groupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance : .
        /// </summary>
        public static string Label_Ins_Naissance {
            get {
                return ResourceManager.GetString("Label_Ins_Naissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom / prénom : .
        /// </summary>
        public static string Label_Ins_NomPrenom {
            get {
                return ResourceManager.GetString("Label_Ins_NomPrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saison : .
        /// </summary>
        public static string Label_Ins_Saison {
            get {
                return ResourceManager.GetString("Label_Ins_Saison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sexe : .
        /// </summary>
        public static string Label_Ins_Sexe {
            get {
                return ResourceManager.GetString("Label_Ins_Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut : .
        /// </summary>
        public static string Label_Ins_Statut {
            get {
                return ResourceManager.GetString("Label_Ins_Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville : .
        /// </summary>
        public static string Label_Ins_Ville {
            get {
                return ResourceManager.GetString("Label_Ins_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. filtré(s) : .
        /// </summary>
        public static string Label_NbFiltre {
            get {
                return ResourceManager.GetString("Label_NbFiltre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. total : .
        /// </summary>
        public static string Label_NbTotal {
            get {
                return ResourceManager.GetString("Label_NbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Année début : .
        /// </summary>
        public static string Label_Sai_AnneeDebut {
            get {
                return ResourceManager.GetString("Label_Sai_AnneeDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Année fin : .
        /// </summary>
        public static string Label_Sai_AnneeFin {
            get {
                return ResourceManager.GetString("Label_Sai_AnneeFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saison courante : .
        /// </summary>
        public static string Label_Sai_SaisonCourante {
            get {
                return ResourceManager.GetString("Label_Sai_SaisonCourante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code postal : .
        /// </summary>
        public static string Label_Vil_CodePostal {
            get {
                return ResourceManager.GetString("Label_Vil_CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom : .
        /// </summary>
        public static string Label_Vil_Nom {
            get {
                return ResourceManager.GetString("Label_Vil_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent non valide. Enregistrement annulé..
        /// </summary>
        public static string Log_Adh_EnregistrementAnnule {
            get {
                return ResourceManager.GetString("Log_Adh_EnregistrementAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent enregistré..
        /// </summary>
        public static string Log_Adh_EnregistrementEffectue {
            get {
                return ResourceManager.GetString("Log_Adh_EnregistrementEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent supprimé..
        /// </summary>
        public static string Log_Adh_EnregistrementSupprime {
            get {
                return ResourceManager.GetString("Log_Adh_EnregistrementSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage du menu GestionAdhesions..
        /// </summary>
        public static string Log_AffichageMenu {
            get {
                return ResourceManager.GetString("Log_AffichageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage de la vue .
        /// </summary>
        public static string Log_AffichageVue {
            get {
                return ResourceManager.GetString("Log_AffichageVue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe non valide. Enregistrement annulé..
        /// </summary>
        public static string Log_Grp_EnregistrementAnnule {
            get {
                return ResourceManager.GetString("Log_Grp_EnregistrementAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe enregistré..
        /// </summary>
        public static string Log_Grp_EnregistrementEffectue {
            get {
                return ResourceManager.GetString("Log_Grp_EnregistrementEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe supprimé..
        /// </summary>
        public static string Log_Grp_EnregistrementSupprime {
            get {
                return ResourceManager.GetString("Log_Grp_EnregistrementSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation du Module GestionAdhesions..
        /// </summary>
        public static string Log_InitialisationModule {
            get {
                return ResourceManager.GetString("Log_InitialisationModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription non valide. Enregistrement annulé..
        /// </summary>
        public static string Log_Ins_EnregistrementAnnule {
            get {
                return ResourceManager.GetString("Log_Ins_EnregistrementAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription enregistrée..
        /// </summary>
        public static string Log_Ins_EnregistrementEffectue {
            get {
                return ResourceManager.GetString("Log_Ins_EnregistrementEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription supprimée..
        /// </summary>
        public static string Log_Ins_EnregistrementSupprime {
            get {
                return ResourceManager.GetString("Log_Ins_EnregistrementSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificat médical remis et cotisation payée. L&apos;inscription est validée..
        /// </summary>
        public static string Log_Ins_StatutValide {
            get {
                return ResourceManager.GetString("Log_Ins_StatutValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saison non valide. Enregistrement annulé..
        /// </summary>
        public static string Log_Sai_EnregistrementAnnule {
            get {
                return ResourceManager.GetString("Log_Sai_EnregistrementAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saison enregistrée..
        /// </summary>
        public static string Log_Sai_EnregistrementEffectue {
            get {
                return ResourceManager.GetString("Log_Sai_EnregistrementEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saison supprimée..
        /// </summary>
        public static string Log_Sai_EnregistrementSupprime {
            get {
                return ResourceManager.GetString("Log_Sai_EnregistrementSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle saison courante : .
        /// </summary>
        public static string Log_Sai_NouvelleSaisonCourante {
            get {
                return ResourceManager.GetString("Log_Sai_NouvelleSaisonCourante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville non valide. Enregistrement annulé..
        /// </summary>
        public static string Log_Vil_EnregistrementAnnule {
            get {
                return ResourceManager.GetString("Log_Vil_EnregistrementAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville enregistrée : .
        /// </summary>
        public static string Log_Vil_EnregistrementEffectue {
            get {
                return ResourceManager.GetString("Log_Vil_EnregistrementEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville supprimée : .
        /// </summary>
        public static string Log_Vil_EnregistrementSupprime {
            get {
                return ResourceManager.GetString("Log_Vil_EnregistrementSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des adhérents.
        /// </summary>
        public static string MenuButton_Adh_List {
            get {
                return ResourceManager.GetString("MenuButton_Adh_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvel adhérent.
        /// </summary>
        public static string MenuButton_Adh_New {
            get {
                return ResourceManager.GetString("MenuButton_Adh_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des groupes.
        /// </summary>
        public static string MenuButton_Grp_List {
            get {
                return ResourceManager.GetString("MenuButton_Grp_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau groupe.
        /// </summary>
        public static string MenuButton_Grp_New {
            get {
                return ResourceManager.GetString("MenuButton_Grp_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des inscriptions.
        /// </summary>
        public static string MenuButton_Ins_List {
            get {
                return ResourceManager.GetString("MenuButton_Ins_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle inscription.
        /// </summary>
        public static string MenuButton_Ins_New {
            get {
                return ResourceManager.GetString("MenuButton_Ins_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des saisons.
        /// </summary>
        public static string MenuButton_Sai_List {
            get {
                return ResourceManager.GetString("MenuButton_Sai_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle saison.
        /// </summary>
        public static string MenuButton_Sai_New {
            get {
                return ResourceManager.GetString("MenuButton_Sai_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des villes.
        /// </summary>
        public static string MenuButton_Vil_List {
            get {
                return ResourceManager.GetString("MenuButton_Vil_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle ville.
        /// </summary>
        public static string MenuButton_Vil_New {
            get {
                return ResourceManager.GetString("MenuButton_Vil_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des adhérents.
        /// </summary>
        public static string MenuHeader_Adh {
            get {
                return ResourceManager.GetString("MenuHeader_Adh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des groupes.
        /// </summary>
        public static string MenuHeader_Grp {
            get {
                return ResourceManager.GetString("MenuHeader_Grp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des inscriptions.
        /// </summary>
        public static string MenuHeader_Ins {
            get {
                return ResourceManager.GetString("MenuHeader_Ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des saisons.
        /// </summary>
        public static string MenuHeader_Sai {
            get {
                return ResourceManager.GetString("MenuHeader_Sai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des villes.
        /// </summary>
        public static string MenuHeader_Vil {
            get {
                return ResourceManager.GetString("MenuHeader_Vil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhésions.
        /// </summary>
        public static string RibbonGroupHeader_Adhesions {
            get {
                return ResourceManager.GetString("RibbonGroupHeader_Adhesions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Référentiel.
        /// </summary>
        public static string RibbonGroupHeader_Referentiel {
            get {
                return ResourceManager.GetString("RibbonGroupHeader_Referentiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhésions.
        /// </summary>
        public static string RibbonTabHeader {
            get {
                return ResourceManager.GetString("RibbonTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent.
        /// </summary>
        public static string Titre_Adh_Formulaire {
            get {
                return ResourceManager.GetString("Titre_Adh_Formulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérents.
        /// </summary>
        public static string Titre_Adh_List {
            get {
                return ResourceManager.GetString("Titre_Adh_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe.
        /// </summary>
        public static string Titre_Grp_Formulaire {
            get {
                return ResourceManager.GetString("Titre_Grp_Formulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupes.
        /// </summary>
        public static string Titre_Grp_List {
            get {
                return ResourceManager.GetString("Titre_Grp_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string Titre_Ins_Formulaire {
            get {
                return ResourceManager.GetString("Titre_Ins_Formulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscriptions.
        /// </summary>
        public static string Titre_Ins_List {
            get {
                return ResourceManager.GetString("Titre_Ins_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saison.
        /// </summary>
        public static string Titre_Sai_Formulaire {
            get {
                return ResourceManager.GetString("Titre_Sai_Formulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisons.
        /// </summary>
        public static string Titre_Sai_List {
            get {
                return ResourceManager.GetString("Titre_Sai_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        public static string Titre_Vil_Formulaire {
            get {
                return ResourceManager.GetString("Titre_Vil_Formulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Villes.
        /// </summary>
        public static string Titre_Vil_List {
            get {
                return ResourceManager.GetString("Titre_Vil_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        public static string Tooltip_Adh_Adresse {
            get {
                return ResourceManager.GetString("Tooltip_Adh_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse e-mail principale.
        /// </summary>
        public static string Tooltip_Adh_EmailPrincipal {
            get {
                return ResourceManager.GetString("Tooltip_Adh_EmailPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse e-mail secondaire.
        /// </summary>
        public static string Tooltip_Adh_EmailSecondaire {
            get {
                return ResourceManager.GetString("Tooltip_Adh_EmailSecondaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse e-mail tertiaire.
        /// </summary>
        public static string Tooltip_Adh_EmailTertiaire {
            get {
                return ResourceManager.GetString("Tooltip_Adh_EmailTertiaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Tooltip_Adh_Nom {
            get {
                return ResourceManager.GetString("Tooltip_Adh_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string Tooltip_Adh_Prenom {
            get {
                return ResourceManager.GetString("Tooltip_Adh_Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° de tél. principal.
        /// </summary>
        public static string Tooltip_Adh_TelPrincipal {
            get {
                return ResourceManager.GetString("Tooltip_Adh_TelPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° de tél. secondaire.
        /// </summary>
        public static string Tooltip_Adh_TelSecondaire {
            get {
                return ResourceManager.GetString("Tooltip_Adh_TelSecondaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° de tél. tertiaire.
        /// </summary>
        public static string Tooltip_Adh_TelTertiaire {
            get {
                return ResourceManager.GetString("Tooltip_Adh_TelTertiaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string Tooltip_Ajouter {
            get {
                return ResourceManager.GetString("Tooltip_Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Tooltip_Annuler {
            get {
                return ResourceManager.GetString("Tooltip_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer.
        /// </summary>
        public static string Tooltip_Editer {
            get {
                return ResourceManager.GetString("Tooltip_Editer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string Tooltip_Enregistrer {
            get {
                return ResourceManager.GetString("Tooltip_Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Définir comme saison courante.
        /// </summary>
        public static string Tooltip_Sai_SaisonCourante {
            get {
                return ResourceManager.GetString("Tooltip_Sai_SaisonCourante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Tooltip_Supprimer {
            get {
                return ResourceManager.GetString("Tooltip_Supprimer", resourceCulture);
            }
        }
    }
}
