//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestAssoc.Modules.GestionAdherents.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestAssoc.Modules.GestionAdherents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes-vous sûr de vouloir supprimer cet adhérent?.
        /// </summary>
        public static string Confirm_SuppressionAdherent {
            get {
                return ResourceManager.GetString("Confirm_SuppressionAdherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet adhérent existe déjà (nom + prénom)..
        /// </summary>
        public static string Err_AdherentExiste {
            get {
                return ResourceManager.GetString("Err_AdherentExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse obligatoire..
        /// </summary>
        public static string Err_AdresseObligatoire {
            get {
                return ResourceManager.GetString("Err_AdresseObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date de naissance saisie est trop ancienne pour le système..
        /// </summary>
        public static string Err_DateNaissanceTropAncienne {
            get {
                return ResourceManager.GetString("Err_DateNaissanceTropAncienne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance obligatoire..
        /// </summary>
        public static string Err_NaissanceObligatoire {
            get {
                return ResourceManager.GetString("Err_NaissanceObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom obligatoire..
        /// </summary>
        public static string Err_NomObligatoire {
            get {
                return ResourceManager.GetString("Err_NomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom obligatoire..
        /// </summary>
        public static string Err_PrenomObligatoire {
            get {
                return ResourceManager.GetString("Err_PrenomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VilleObligatoire..
        /// </summary>
        public static string Err_VilleObligatoire {
            get {
                return ResourceManager.GetString("Err_VilleObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string Header_Actions {
            get {
                return ResourceManager.GetString("Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérents.
        /// </summary>
        public static string Header_Adherents {
            get {
                return ResourceManager.GetString("Header_Adherents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        public static string Header_Details {
            get {
                return ResourceManager.GetString("Header_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats.
        /// </summary>
        public static string Header_Statistiques {
            get {
                return ResourceManager.GetString("Header_Statistiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse : .
        /// </summary>
        public static string Label_Adresse {
            get {
                return ResourceManager.GetString("Label_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à an(s).
        /// </summary>
        public static string Label_Ans {
            get {
                return ResourceManager.GetString("Label_Ans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaires : .
        /// </summary>
        public static string Label_Commentaire {
            get {
                return ResourceManager.GetString("Label_Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mails : .
        /// </summary>
        public static string Label_Emails {
            get {
                return ResourceManager.GetString("Label_Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance : .
        /// </summary>
        public static string Label_Naissance {
            get {
                return ResourceManager.GetString("Label_Naissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. filtré(s) : .
        /// </summary>
        public static string Label_NbFiltre {
            get {
                return ResourceManager.GetString("Label_NbFiltre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. total : .
        /// </summary>
        public static string Label_NbTotal {
            get {
                return ResourceManager.GetString("Label_NbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom / prénom : .
        /// </summary>
        public static string Label_NomPrenom {
            get {
                return ResourceManager.GetString("Label_NomPrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sexe : .
        /// </summary>
        public static string Label_Sexe {
            get {
                return ResourceManager.GetString("Label_Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphones : .
        /// </summary>
        public static string Label_Telephones {
            get {
                return ResourceManager.GetString("Label_Telephones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville : .
        /// </summary>
        public static string Label_Ville {
            get {
                return ResourceManager.GetString("Label_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage du menu GestionAdherents.
        /// </summary>
        public static string Log_AffichageMenu {
            get {
                return ResourceManager.GetString("Log_AffichageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage de la vue .
        /// </summary>
        public static string Log_AffichageVue {
            get {
                return ResourceManager.GetString("Log_AffichageVue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent non valide. Enregistrement annulé..
        /// </summary>
        public static string Log_EnregistrementAnnule {
            get {
                return ResourceManager.GetString("Log_EnregistrementAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent enregistré..
        /// </summary>
        public static string Log_EnregistrementEffectue {
            get {
                return ResourceManager.GetString("Log_EnregistrementEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement supprimé..
        /// </summary>
        public static string Log_EnregistrementSupprime {
            get {
                return ResourceManager.GetString("Log_EnregistrementSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation du Module GestionAdherents..
        /// </summary>
        public static string Log_InitialisationModule {
            get {
                return ResourceManager.GetString("Log_InitialisationModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des adhérents.
        /// </summary>
        public static string MenuButton_List {
            get {
                return ResourceManager.GetString("MenuButton_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvel adhérent.
        /// </summary>
        public static string MenuButton_New {
            get {
                return ResourceManager.GetString("MenuButton_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des adhérents.
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent.
        /// </summary>
        public static string Titre_Formulaire {
            get {
                return ResourceManager.GetString("Titre_Formulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérents.
        /// </summary>
        public static string Titre_List {
            get {
                return ResourceManager.GetString("Titre_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        public static string Tooltip_Adresse {
            get {
                return ResourceManager.GetString("Tooltip_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string Tooltip_Ajouter {
            get {
                return ResourceManager.GetString("Tooltip_Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Tooltip_Annuler {
            get {
                return ResourceManager.GetString("Tooltip_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer.
        /// </summary>
        public static string Tooltip_Editer {
            get {
                return ResourceManager.GetString("Tooltip_Editer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse e-mail principale.
        /// </summary>
        public static string Tooltip_EmailPrincipal {
            get {
                return ResourceManager.GetString("Tooltip_EmailPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse e-mail secondaire.
        /// </summary>
        public static string Tooltip_EmailSecondaire {
            get {
                return ResourceManager.GetString("Tooltip_EmailSecondaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse e-mail tertiaire.
        /// </summary>
        public static string Tooltip_EmailTertiaire {
            get {
                return ResourceManager.GetString("Tooltip_EmailTertiaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string Tooltip_Enregistrer {
            get {
                return ResourceManager.GetString("Tooltip_Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Tooltip_Nom {
            get {
                return ResourceManager.GetString("Tooltip_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string Tooltip_Prenom {
            get {
                return ResourceManager.GetString("Tooltip_Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Tooltip_Supprimer {
            get {
                return ResourceManager.GetString("Tooltip_Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° de tél. principal.
        /// </summary>
        public static string Tooltip_TelPrincipal {
            get {
                return ResourceManager.GetString("Tooltip_TelPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° de tél. secondaire.
        /// </summary>
        public static string Tooltip_TelSecondaire {
            get {
                return ResourceManager.GetString("Tooltip_TelSecondaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° de tél. tertiaire.
        /// </summary>
        public static string Tooltip_TelTertiaire {
            get {
                return ResourceManager.GetString("Tooltip_TelTertiaire", resourceCulture);
            }
        }
    }
}
