//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestAssoc.Modules.GestionAdherents.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestAssoc.Modules.GestionAdherents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet adhérent existe déjà (nom + prénom)..
        /// </summary>
        public static string Err_AdherentExiste {
            get {
                return ResourceManager.GetString("Err_AdherentExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse obligatoire..
        /// </summary>
        public static string Err_AdresseObligatoire {
            get {
                return ResourceManager.GetString("Err_AdresseObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de naissance obligatoire..
        /// </summary>
        public static string Err_NaissanceObligatoire {
            get {
                return ResourceManager.GetString("Err_NaissanceObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom obligatoire..
        /// </summary>
        public static string Err_NomObligatoire {
            get {
                return ResourceManager.GetString("Err_NomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom obligatoire..
        /// </summary>
        public static string Err_PrenomObligatoire {
            get {
                return ResourceManager.GetString("Err_PrenomObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VilleObligatoire..
        /// </summary>
        public static string Err_VilleObligatoire {
            get {
                return ResourceManager.GetString("Err_VilleObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage du menu GestionAdherents.
        /// </summary>
        public static string Log_AffichageMenu {
            get {
                return ResourceManager.GetString("Log_AffichageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage de la vue .
        /// </summary>
        public static string Log_AffichageVue {
            get {
                return ResourceManager.GetString("Log_AffichageVue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent non valide. Enregistrement annulé..
        /// </summary>
        public static string Log_EnregistrementAnnule {
            get {
                return ResourceManager.GetString("Log_EnregistrementAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement effectué..
        /// </summary>
        public static string Log_EnregistrementEffectue {
            get {
                return ResourceManager.GetString("Log_EnregistrementEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement supprimé..
        /// </summary>
        public static string Log_EnregistrementSupprime {
            get {
                return ResourceManager.GetString("Log_EnregistrementSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation du Module GestionAdherents..
        /// </summary>
        public static string Log_InitialisationModule {
            get {
                return ResourceManager.GetString("Log_InitialisationModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des adhérents.
        /// </summary>
        public static string MenuButton_List {
            get {
                return ResourceManager.GetString("MenuButton_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvel adhérent.
        /// </summary>
        public static string MenuButton_New {
            get {
                return ResourceManager.GetString("MenuButton_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des adhérents.
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
    }
}
