//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestAssoc.Modules.GestionGroupes.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestAssoc.Modules.GestionGroupes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce groupe existe déjà (nom + créneau)..
        /// </summary>
        public static string Err_GroupeExiste {
            get {
                return ResourceManager.GetString("Err_GroupeExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure de fin doit être strictement supérieure à l&apos;heure de début..
        /// </summary>
        public static string Err_HeureDebutHeureFin {
            get {
                return ResourceManager.GetString("Err_HeureDebutHeureFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure de début obligatoire..
        /// </summary>
        public static string Err_HeureDebutObligatoire {
            get {
                return ResourceManager.GetString("Err_HeureDebutObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure de fin obligatoire..
        /// </summary>
        public static string Err_HeureFinObligatoire {
            get {
                return ResourceManager.GetString("Err_HeureFinObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom obligatoire..
        /// </summary>
        public static string Err_LibelleObligatoire {
            get {
                return ResourceManager.GetString("Err_LibelleObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string Header_Actions {
            get {
                return ResourceManager.GetString("Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        public static string Header_Details {
            get {
                return ResourceManager.GetString("Header_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupes.
        /// </summary>
        public static string Header_List {
            get {
                return ResourceManager.GetString("Header_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats.
        /// </summary>
        public static string Header_Statistiques {
            get {
                return ResourceManager.GetString("Header_Statistiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaires : .
        /// </summary>
        public static string Label_Commentaire {
            get {
                return ResourceManager.GetString("Label_Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créneau : .
        /// </summary>
        public static string Label_Creneau {
            get {
                return ResourceManager.GetString("Label_Creneau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure de début : .
        /// </summary>
        public static string Label_HeureDebut {
            get {
                return ResourceManager.GetString("Label_HeureDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure de fin : .
        /// </summary>
        public static string Label_HeureFin {
            get {
                return ResourceManager.GetString("Label_HeureFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jour : .
        /// </summary>
        public static string Label_Jour {
            get {
                return ResourceManager.GetString("Label_Jour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. filtré(s) :.
        /// </summary>
        public static string Label_NbFiltre {
            get {
                return ResourceManager.GetString("Label_NbFiltre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. places : .
        /// </summary>
        public static string Label_NbPlaces {
            get {
                return ResourceManager.GetString("Label_NbPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. total : .
        /// </summary>
        public static string Label_NbTotal {
            get {
                return ResourceManager.GetString("Label_NbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom : .
        /// </summary>
        public static string Label_Nom {
            get {
                return ResourceManager.GetString("Label_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saison : .
        /// </summary>
        public static string Label_Saison {
            get {
                return ResourceManager.GetString("Label_Saison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage du menu GestionGroupes.
        /// </summary>
        public static string Log_AffichageMenu {
            get {
                return ResourceManager.GetString("Log_AffichageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage de la vue .
        /// </summary>
        public static string Log_AffichageVue {
            get {
                return ResourceManager.GetString("Log_AffichageVue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe non valide. Enregistrement annulé..
        /// </summary>
        public static string Log_EnregistrementAnnule {
            get {
                return ResourceManager.GetString("Log_EnregistrementAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement effectué..
        /// </summary>
        public static string Log_EnregistrementEffectue {
            get {
                return ResourceManager.GetString("Log_EnregistrementEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe supprimé..
        /// </summary>
        public static string Log_EnregistrementSupprime {
            get {
                return ResourceManager.GetString("Log_EnregistrementSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation du Module GestionGroupes..
        /// </summary>
        public static string Log_InitModule {
            get {
                return ResourceManager.GetString("Log_InitModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consulter.
        /// </summary>
        public static string MenuButton_List {
            get {
                return ResourceManager.GetString("MenuButton_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau groupe.
        /// </summary>
        public static string MenuButton_New {
            get {
                return ResourceManager.GetString("MenuButton_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des groupes.
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe.
        /// </summary>
        public static string Titre_Edition {
            get {
                return ResourceManager.GetString("Titre_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupes.
        /// </summary>
        public static string Titre_List {
            get {
                return ResourceManager.GetString("Titre_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string Tooltip_Ajouter {
            get {
                return ResourceManager.GetString("Tooltip_Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Tooltip_Annuler {
            get {
                return ResourceManager.GetString("Tooltip_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer.
        /// </summary>
        public static string Tooltip_Editer {
            get {
                return ResourceManager.GetString("Tooltip_Editer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string Tooltip_Enregistrer {
            get {
                return ResourceManager.GetString("Tooltip_Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Tooltip_Supprimer {
            get {
                return ResourceManager.GetString("Tooltip_Supprimer", resourceCulture);
            }
        }
    }
}
