//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestAssoc.Modules.GestionInscriptions.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestAssoc.Modules.GestionInscriptions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent obligatoire..
        /// </summary>
        public static string Err_AdherentObligatoire {
            get {
                return ResourceManager.GetString("Err_AdherentObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe obligatoire..
        /// </summary>
        public static string Err_GroupeObligatoire {
            get {
                return ResourceManager.GetString("Err_GroupeObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette inscription existe déjà (adhérent + groupe)..
        /// </summary>
        public static string Err_InscriptionExiste {
            get {
                return ResourceManager.GetString("Err_InscriptionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string Header_Actions {
            get {
                return ResourceManager.GetString("Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adhérent.
        /// </summary>
        public static string Header_Adherent {
            get {
                return ResourceManager.GetString("Header_Adherent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string Header_Inscription {
            get {
                return ResourceManager.GetString("Header_Inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscriptions.
        /// </summary>
        public static string Header_List {
            get {
                return ResourceManager.GetString("Header_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats.
        /// </summary>
        public static string Header_Statistiques {
            get {
                return ResourceManager.GetString("Header_Statistiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à an(s).
        /// </summary>
        public static string Label_Ans {
            get {
                return ResourceManager.GetString("Label_Ans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificat médical : .
        /// </summary>
        public static string Label_CertificatMedical {
            get {
                return ResourceManager.GetString("Label_CertificatMedical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaires : .
        /// </summary>
        public static string Label_Commentaire {
            get {
                return ResourceManager.GetString("Label_Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cotisation : .
        /// </summary>
        public static string Label_Cotisation {
            get {
                return ResourceManager.GetString("Label_Cotisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe : .
        /// </summary>
        public static string Label_Groupe {
            get {
                return ResourceManager.GetString("Label_Groupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Né le : .
        /// </summary>
        public static string Label_Naissance {
            get {
                return ResourceManager.GetString("Label_Naissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. filtré(s) :.
        /// </summary>
        public static string Label_NbFiltre {
            get {
                return ResourceManager.GetString("Label_NbFiltre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. total : .
        /// </summary>
        public static string Label_NbTotal {
            get {
                return ResourceManager.GetString("Label_NbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom/Prénom : .
        /// </summary>
        public static string Label_NomPrenom {
            get {
                return ResourceManager.GetString("Label_NomPrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saison : .
        /// </summary>
        public static string Label_Saison {
            get {
                return ResourceManager.GetString("Label_Saison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sexe : .
        /// </summary>
        public static string Label_Sexe {
            get {
                return ResourceManager.GetString("Label_Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut : .
        /// </summary>
        public static string Label_Statut {
            get {
                return ResourceManager.GetString("Label_Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville : .
        /// </summary>
        public static string Label_Ville {
            get {
                return ResourceManager.GetString("Label_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage du menu GestionInscriptions.
        /// </summary>
        public static string Log_AffichageMenu {
            get {
                return ResourceManager.GetString("Log_AffichageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage de la vue .
        /// </summary>
        public static string Log_AffichageVue {
            get {
                return ResourceManager.GetString("Log_AffichageVue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription non valide. Enregistrement annulé..
        /// </summary>
        public static string Log_EnregistrementAnnule {
            get {
                return ResourceManager.GetString("Log_EnregistrementAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement effectué..
        /// </summary>
        public static string Log_EnregistrementEffectue {
            get {
                return ResourceManager.GetString("Log_EnregistrementEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription supprimée..
        /// </summary>
        public static string Log_EnregistrementSupprime {
            get {
                return ResourceManager.GetString("Log_EnregistrementSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription supprimée..
        /// </summary>
        public static string Log_EnregistrementSupprime1 {
            get {
                return ResourceManager.GetString("Log_EnregistrementSupprime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation du Module GestionInscriptions..
        /// </summary>
        public static string Log_InitModule {
            get {
                return ResourceManager.GetString("Log_InitModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consulter.
        /// </summary>
        public static string MenuButton_List {
            get {
                return ResourceManager.GetString("MenuButton_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle inscription.
        /// </summary>
        public static string MenuButton_New {
            get {
                return ResourceManager.GetString("MenuButton_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des inscriptions.
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscriptions.
        /// </summary>
        public static string Titre_Consultation {
            get {
                return ResourceManager.GetString("Titre_Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string Titre_Formulaire {
            get {
                return ResourceManager.GetString("Titre_Formulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string Tooltip_Ajouter {
            get {
                return ResourceManager.GetString("Tooltip_Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Tooltip_Annuler {
            get {
                return ResourceManager.GetString("Tooltip_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer.
        /// </summary>
        public static string Tooltip_Editer {
            get {
                return ResourceManager.GetString("Tooltip_Editer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string Tooltip_Enregistrer {
            get {
                return ResourceManager.GetString("Tooltip_Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Tooltip_Supprimer {
            get {
                return ResourceManager.GetString("Tooltip_Supprimer", resourceCulture);
            }
        }
    }
}
